/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package br.com.cartola.liga;

public class Login {
	@org.codehaus.jackson.annotate.JsonProperty("glbId")
	private java.lang.String glbid;

 	public void setGlbid(java.lang.String glbid) {
		this.glbid = glbid;
	}

	public java.lang.String getGlbid() {
		return glbid;
	}

	@org.codehaus.jackson.annotate.JsonProperty("id")
	private java.lang.String id;

 	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("userMessage")
	private java.lang.String usermessage;

 	public void setUsermessage(java.lang.String usermessage) {
		this.usermessage = usermessage;
	}

	public java.lang.String getUsermessage() {
		return usermessage;
	}

}